### ISSUE TITLE
conda installation fails from README instructions

### ISSUE THREAD

**Issue by rmrao** [Merck/BioPhi#10]
Just a quick issue - following the conda installation instructions in the README fails with a strange glibc version error for me (I think it's related to [this issue](https://github.com/rapidsai/cuml/issues/3108)). 

Looks like the problem is that you actually need the additional channels from the environment.yml file ( `conda-forge` and/or `nodefaults`) for the installation to succeed, so the command should be

`conda install biophi -c bioconda -c conda-forge -c nodefaults`

**Comment by prihoda** [comment]
Hi @rmrao thanks for reporting this. So just to clarify, you don't have `conda-forge` in your `conda config --show channels` ?

**Comment by rmrao** [comment]
If I follow the README instructions directly:

```
# Recommended: Create a separate BioPhi environment
conda create -n biophi python=3.8
conda activate biophi

# Install BioPhi
conda install -c bioconda biophi
```

Then I do not. Adding `-c conda-forge` to the final line solves the issue.

**Comment by prihoda** [comment]
Ok I added instructions to add these channels: https://github.com/Merck/BioPhi/commit/6165cff554a640d36d69e2165f1e0cbe3a29b1fd
