### ISSUE TITLE
Running at local webpage

### ISSUE THREAD

**Issue by kimdn** [Merck/BioPhi#23]
At
http://localhost:5000/humanization/designer/

I see
`Error: [Errno 2] No such file or directory: 'hmmscan'`

Can I get any advice?

**Comment by prihoda** [comment]
Hi @kimdn can you share the full error output? Thanks

**Comment by prihoda** [comment]
I added some instructions on running through Docker, that might work better for you: https://github.com/Merck/BioPhi/blob/main/README.md#run-biophi-using-provided-docker-image

**Comment by Pkulyte** [comment]
Hello @kimdn  did you resolve it? Could you share solution?
