### ISSUE TITLE
Vernier CDR Grafting

### ISSUE THREAD

**Issue by salvatta2** [Merck/BioPhi#26]
Hi, I see that the CDR grafting option in the server performs straight grafting. Is there any way to automatically perform "Vernier" CDR grafting while retaining key "back-mutations" in the Vernier zones (as you describe in the paper)?
Thank you!!
SG

**Comment by prihoda** [comment]
Hi @salvatta2 sorry for the late reply. You can use "Kabat + Vernier" CDR definition in the settings, this will avoid any mutations in those regions.

<img width="710" alt="image" src="https://user-images.githubusercontent.com/2894124/195985191-d87c6895-1312-472c-96e9-0d6e42d418e5.png">

**Comment by salvatta2** [comment]
Hi David,
many thanks for your reply, sorry my fault I didn't see this on the web
server. Now clear!
Kind regards,
Salva
