### ISSUE TITLE
Jobs stay at "waiting in queue" at BioPhi server

### ISSUE THREAD

**Issue by C9Tang** [Merck/BioPhi#55]
I used the server sometime earlier this year and it went find and will get results back in couple of minutes. 
However, lately I submitted a couple of calculations to either Evaluate humanness or Humanize antibody, the page kept refreshing with "Tasks are waiting in queue" for 24hr and did not show any results. When went back to the link a day later, it said "Results are only stored a limited amount of time, please submit the form again".

**Comment by Tasshitra** [comment]
I'm having the same issue here.

**Comment by keithgmitchell** [comment]
Same here

**Comment by hicks139** [comment]
Yes, this issue is of interest to me as well.

**Comment by prihoda** [comment]
Hi everyone, thanks for reporting this, the server was restarted, please try now

**Comment by Immunoking** [comment]
After your server reset, everything worked again for the last 3 weeks. Now I am again getting the same message for the last hours. 

Could you help out/restart the server?

**Comment by hicks139** [comment]
Following up with Immunoking's comment - have you been able to check on the server to see why BioPhi isn't working?

**Comment by Immunoking** [comment]
I think the server was online during Christmas, but is unavailable again unfortunately.

**Comment by prihoda** [comment]
The server has been restarted, sorry for the downtime
