### ISSUE TITLE
Task is waiting in queue...

### ISSUE THREAD

**Issue by Immunoking** [Merck/BioPhi#56]
Recently the server was resetted to resolve this issue. After 3 weeks of use, the issue arose once more. 

Could you please reset the server on the website?

**Comment by Tasshitra** [comment]
Yes, because the task is still waiting in queue for 24 hours and couldnt get the results.

**Comment by CarolJia** [comment]
Same here, Hope the developers can restart the server.

**Comment by prihoda** [comment]
The server has been restarted, sorry for the downtime
